name: Deploy to server

on:
  pull_request:
    # types: [closed]
    branches:
      - preprod

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 51.15.229.53 >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz --delete ./ johannes@51.15.229.53:/home/johannes/test/skill-quest-front/
      - name: Start Docker Compose on server
        run: |
          ssh johannes@51.15.229.53 "cd /home/johannes/test && docker-compose up -d"
