name: Notify Discord on PR

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - develop
      - main
      - preprod

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                     "username": "GitHub Bot",
                     "content": "\n\n@everyone 📣 Nouvelle Pull Request vers `${{ github.base_ref }}` par **${{ github.actor }}**\nmessage: ${{ github.event.pull_request.title }}\n${{ github.event.pull_request.html_url }}"
                   }' \
               $DISCORD_WEBHOOK_URL
