import type { Skill } from './skills.types';
import { SkillDifficulty, SkillStatus } from './skills.types';

export const skillsMock: Skill[] = [
  {
    id: '1',
    title: 'Écriture',
    description: 'Améliorer ses capacités rédactionnelles et sa créativité à l\'écrit.',
    category: 'Développement personnel',
    difficulty: SkillDifficulty.Medium,
    status: SkillStatus.InProgress,
    createdAt: '2024-05-01T10:00:00Z',
  },
  {
    id: '2',
    title: 'Rigueur',
    description: 'Développer la constance et la discipline dans ses activités quotidiennes.',
    category: 'Développement personnel',
    difficulty: SkillDifficulty.Hard,
    status: SkillStatus.Finished,
    createdAt: '2024-05-02T10:00:00Z',
  },
  {
    id: '3',
    title: 'Sommeil',
    description: 'Optimiser la qualité et la régularité de son sommeil.',
    category: 'Santé',
    difficulty: SkillDifficulty.Easy,
    status: SkillStatus.NotStarted,
    createdAt: '2024-05-03T10:00:00Z',
  },
  {
    id: '4',
    title: 'Lecture',
    description: 'Lire régulièrement pour enrichir ses connaissances et sa curiosité.',
    category: 'Culture',
    difficulty: SkillDifficulty.Medium,
    status: SkillStatus.Draft,
    createdAt: '2024-05-04T10:00:00Z',
  },
  {
    id: '5',
    title: 'Gestion des émotions',
    description: 'Apprendre à reconnaître et à gérer ses émotions efficacement.',
    category: 'Développement personnel',
    difficulty: SkillDifficulty.Hard,
    status: SkillStatus.InProgress,
    createdAt: '2024-05-05T10:00:00Z',
  },
  {
    id: '6',
    title: 'Alimentation',
    description: 'Adopter une alimentation saine et équilibrée.',
    category: 'Santé',
    difficulty: SkillDifficulty.Easy,
    status: SkillStatus.NotStarted,
    createdAt: '2024-05-06T10:00:00Z',
  },
  {
    id: '7',
    title: 'Art',
    description: 'Développer ses compétences artistiques et sa sensibilité.',
    category: 'Créativité',
    difficulty: SkillDifficulty.Medium,
    status: SkillStatus.Draft,
    createdAt: '2024-05-07T10:00:00Z',
  },
  {
    id: '8',
    title: 'Gestion financière',
    description: 'Mieux gérer son budget et ses finances personnelles.',
    category: 'Vie pratique',
    difficulty: SkillDifficulty.Hard,
    status: SkillStatus.Finished,
    createdAt: '2024-05-08T10:00:00Z',
  },
  {
    id: '9',
    title: 'Sport',
    description: 'Améliorer sa condition physique et sa santé.',
    category: 'Santé',
    difficulty: SkillDifficulty.Medium,
    status: SkillStatus.InProgress,
    createdAt: '2024-05-09T10:00:00Z',
  },
  {
    id: '10',
    title: 'Programmation',
    description: 'Développer des compétences en développement logiciel.',
    category: 'Tech',
    difficulty: SkillDifficulty.Hard,
    status: SkillStatus.Draft,
    createdAt: '2024-05-10T10:00:00Z',
  },
  {
    id: '11',
    title: 'Cuisine',
    description: 'Apprendre à cuisiner des plats sains et savoureux.',
    category: 'Vie pratique',
    difficulty: SkillDifficulty.Easy,
    status: SkillStatus.NotStarted,
    createdAt: '2024-05-11T10:00:00Z',
  },
  {
    id: '12',
    title: 'Photographie',
    description: 'Maîtriser les bases de la photographie et de la retouche.',
    category: 'Créativité',
    difficulty: SkillDifficulty.Medium,
    status: SkillStatus.InProgress,
    createdAt: '2024-05-12T10:00:00Z',
  },
  {
    id: '13',
    title: 'Jardinage',
    description: 'Entretenir un jardin et cultiver ses propres légumes.',
    category: 'Nature',
    difficulty: SkillDifficulty.Easy,
    status: SkillStatus.Finished,
    createdAt: '2024-05-13T10:00:00Z',
  },
  {
    id: '14',
    title: 'Musique',
    description: 'Apprendre à jouer d’un instrument de musique.',
    category: 'Créativité',
    difficulty: SkillDifficulty.Medium,
    status: SkillStatus.Draft,
    createdAt: '2024-05-14T10:00:00Z',
  },
  {
    id: '15',
    title: 'Lecture rapide',
    description: 'Développer des techniques de lecture rapide.',
    category: 'Culture',
    difficulty: SkillDifficulty.Hard,
    status: SkillStatus.NotStarted,
    createdAt: '2024-05-15T10:00:00Z',
  },
  {
    id: '16',
    title: 'Méditation',
    description: 'Découvrir les bienfaits de la méditation quotidienne.',
    category: 'Développement personnel',
    difficulty: SkillDifficulty.Easy,
    status: SkillStatus.Finished,
    createdAt: '2024-05-16T10:00:00Z',
  },
  {
    id: '17',
    title: 'Langues étrangères',
    description: 'Apprendre une nouvelle langue pour voyager.',
    category: 'Culture',
    difficulty: SkillDifficulty.Medium,
    status: SkillStatus.InProgress,
    createdAt: '2024-05-17T10:00:00Z',
  },
  {
    id: '18',
    title: 'Développement web',
    description: 'Créer des sites web modernes et responsives.',
    category: 'Tech',
    difficulty: SkillDifficulty.Hard,
    status: SkillStatus.Draft,
    createdAt: '2024-05-18T10:00:00Z',
  },
];
