import type { Skill } from "./skills.type";
import { Difficulty, Status } from "./skills.type";

export const difficultyConfig = {
  Facile: {
    icon: "🟢",
    className:
      "bg-green-100 text-green-800 border-green-200 dark:bg-green-900/20 dark:text-green-400 dark:border-green-800",
  },
  Moyen: {
    icon: "🟡",
    className:
      "bg-yellow-100 text-yellow-800 border-yellow-200 dark:bg-yellow-900/20 dark:text-yellow-400 dark:border-yellow-800",
  },
  Difficile: {
    icon: "🔴",
    className: "bg-red-100 text-red-800 border-red-200 dark:bg-red-900/20 dark:text-red-400 dark:border-red-800",
  },
};

export const statusConfig = {
  not_started: {
    icon: "⏳",
    label: "Non commencé",
    className: "bg-gray-100 text-gray-700 border-gray-200 dark:bg-gray-800 dark:text-gray-300 dark:border-gray-700",
  },
  in_progress: {
    icon: "🚀",
    label: "En cours",
    className:
      "bg-purple-100 text-purple-800 border-purple-200 dark:bg-purple-900/20 dark:text-purple-400 dark:border-purple-800",
  },
  completed: {
    icon: "✅",
    label: "Terminé",
    className:
      "bg-green-100 text-green-800 border-green-200 dark:bg-green-900/20 dark:text-green-400 dark:border-green-800",
  },
  draft: {
    icon: "📝",
    label: "Brouillon",
    className:
      "bg-orange-100 text-orange-700 border-orange-200 dark:bg-orange-900/20 dark:text-orange-400 dark:border-orange-800",
  },
};

export const statCards = [
  {
    key: "total",
    title: "Total",
    icon: "🎯",
    color: "text-blue-600",
  },
  {
    key: "completed",
    title: "Terminés",
    icon: "✅",
    color: "text-green-600",
  },
  {
    key: "inProgress",
    title: "En cours",
    icon: "🚀",
    color: "text-purple-600",
  },
  {
    key: "notStarted",
    title: "Non commencés",
    icon: "⏳",
    color: "text-gray-600",
  },
  {
    key: "draft",
    title: "Brouillons",
    icon: "📝",
    color: "text-orange-600",
  },
  {
    key: "averageProgress",
    title: "Progression moy.",
    icon: "📊",
    color: "text-indigo-600",
  },
];

export const COLORS = ["#fff", "#facc15", "#a78bfa"];

export const mockedSkills: Skill[] = [
  {
    id: "1",
    title: "Apprendre React",
    description: "Maîtriser les fondamentaux de React et créer des applications modernes",
    difficulty: Difficulty.Moyen,
    duration: 120,
    status: Status.InProgress,
    category: "Développement Web",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    progress: 65,
    questsCount: 8,
  },
  {
    id: "2",
    title: "Découvrir TypeScript",
    description: "Apprendre TypeScript pour un développement plus robuste",
    difficulty: Difficulty.Facile,
    duration: 90,
    status: Status.NotStarted,
    category: "Développement Web",
    createdAt: "2024-01-18T09:00:00Z",
    updatedAt: "2024-01-18T09:00:00Z",
    progress: 0,
    questsCount: 5,
  },
  {
    id: "3",
    title: "Créer un projet Vite",
    description: "Configurer et optimiser un projet avec Vite",
    difficulty: Difficulty.Facile,
    duration: 60,
    status: Status.Completed,
    category: "Outils",
    createdAt: "2024-01-10T11:00:00Z",
    updatedAt: "2024-01-12T16:45:00Z",
    progress: 100,
    questsCount: 3,
  },
  {
    id: "4",
    title: "Maîtriser les Hooks React",
    description: "Utiliser efficacement les hooks personnalisés et les hooks natifs",
    difficulty: Difficulty.Difficile,
    duration: 180,
    status: Status.Draft,
    category: "Développement Web",
    createdAt: "2024-01-22T08:00:00Z",
    updatedAt: "2024-01-22T08:00:00Z",
    progress: 0,
    questsCount: 12,
  },
  {
    id: "5",
    title: "Design System avec Tailwind",
    description: "Créer un système de design cohérent avec Tailwind CSS",
    difficulty: Difficulty.Moyen,
    duration: 150,
    status: Status.InProgress,
    category: "Design",
    createdAt: "2024-01-16T13:00:00Z",
    updatedAt: "2024-01-21T10:15:00Z",
    progress: 35,
    questsCount: 7,
  },
  {
    id: "6",
    title: "API REST avec Express",
    description: "Développer des APIs RESTful avec Node.js et Express",
    difficulty: Difficulty.Moyen,
    duration: 200,
    status: Status.NotStarted,
    category: "Backend",
    createdAt: "2024-01-25T09:00:00Z",
    updatedAt: "2024-01-25T09:00:00Z",
    progress: 0,
    questsCount: 10,
  },
  {
    id: "7",
    title: "Base de données MongoDB",
    description: "Apprendre à utiliser MongoDB pour le stockage de données",
    difficulty: Difficulty.Facile,
    duration: 100,
    status: Status.Completed,
    category: "Base de données",
    createdAt: "2024-01-08T14:00:00Z",
    updatedAt: "2024-01-15T11:30:00Z",
    progress: 100,
    questsCount: 6,
  },
  {
    id: "8",
    title: "Tests unitaires avec Jest",
    description: "Écrire des tests unitaires efficaces avec Jest",
    difficulty: Difficulty.Moyen,
    duration: 120,
    status: Status.InProgress,
    category: "Tests",
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-01-23T16:20:00Z",
    progress: 45,
    questsCount: 8,
  },
  {
    id: "9",
    title: "Déploiement avec Docker",
    description: "Containeriser et déployer des applications avec Docker",
    difficulty: Difficulty.Difficile,
    duration: 180,
    status: Status.Draft,
    category: "DevOps",
    createdAt: "2024-01-28T08:00:00Z",
    updatedAt: "2024-01-28T08:00:00Z",
    progress: 0,
    questsCount: 15,
  },
  {
    id: "10",
    title: "GraphQL avec Apollo",
    description: "Implémenter GraphQL avec Apollo Client et Server",
    difficulty: Difficulty.Difficile,
    duration: 240,
    status: Status.NotStarted,
    category: "API",
    createdAt: "2024-01-30T11:00:00Z",
    updatedAt: "2024-01-30T11:00:00Z",
    progress: 0,
    questsCount: 12,
  },
  {
    id: "11",
    title: "Machine Learning avec Python",
    description: "Introduction au machine learning avec scikit-learn et TensorFlow",
    difficulty: Difficulty.Difficile,
    duration: 300,
    status: Status.NotStarted,
    category: "IA/ML",
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-02-01T10:00:00Z",
    progress: 0,
    questsCount: 20,
  },
  {
    id: "12",
    title: "Cybersécurité Web",
    description: "Sécuriser les applications web contre les vulnérabilités courantes",
    difficulty: Difficulty.Moyen,
    duration: 160,
    status: Status.InProgress,
    category: "Sécurité",
    createdAt: "2024-01-27T14:00:00Z",
    updatedAt: "2024-02-02T09:15:00Z",
    progress: 25,
    questsCount: 9,
  },
  {
    id: "13",
    title: "Microservices avec Spring Boot",
    description: "Développer des microservices avec Spring Boot et Java",
    difficulty: Difficulty.Difficile,
    duration: 280,
    status: Status.Draft,
    category: "Backend",
    createdAt: "2024-02-03T08:00:00Z",
    updatedAt: "2024-02-03T08:00:00Z",
    progress: 0,
    questsCount: 18,
  },
  {
    id: "14",
    title: "Flutter pour le mobile",
    description: "Créer des applications mobiles cross-platform avec Flutter",
    difficulty: Difficulty.Moyen,
    duration: 220,
    status: Status.NotStarted,
    category: "Mobile",
    createdAt: "2024-02-05T11:00:00Z",
    updatedAt: "2024-02-05T11:00:00Z",
    progress: 0,
    questsCount: 14,
  },
  {
    id: "15",
    title: "Blockchain et Smart Contracts",
    description: "Développer des smart contracts avec Solidity et Ethereum",
    difficulty: Difficulty.Difficile,
    duration: 320,
    status: Status.Draft,
    category: "Blockchain",
    createdAt: "2024-02-07T09:00:00Z",
    updatedAt: "2024-02-07T09:00:00Z",
    progress: 0,
    questsCount: 16,
  },
];
